### ISSUE TITLE
Build doesn't work

### ISSUE THREAD

**Issue by khoi-nguyen** [peerreynders/solid-start-ws-demo#2]
When I try to build the project, it doesn't work.

```
$ npm run build

> build
> vinxi build

vinxi v0.3.14


⚙  Building your app...


📦 Compiling ssr router...
vinxi building router ssr in http mode
vite v5.4.4 building SSR bundle for production...
✓ 11 modules transformed.
x Build failed in 214ms

[8:22:52 AM]  ERROR  [commonjs--resolver] No known conditions for "./routes" specifier in "vinxi" package

  at e (node_modules/vite/dist/node/chunks/dep-BEhTnQAI.js:45978:25)
  at n (node_modules/vite/dist/node/chunks/dep-BEhTnQAI.js:45978:646)
  at o (node_modules/vite/dist/node/chunks/dep-BEhTnQAI.js:45978:1297)
  at resolveExportsOrImports (node_modules/vite/dist/node/chunks/dep-BEhTnQAI.js:46599:18)
  at resolveDeepImport (node_modules/vite/dist/node/chunks/dep-BEhTnQAI.js:46622:25)
  at tryNodeResolve (node_modules/vite/dist/node/chunks/dep-BEhTnQAI.js:46387:16)
  at Object.resolveId (node_modules/vite/dist/node/chunks/dep-BEhTnQAI.js:46137:19)
  at Object.handler (node_modules/vite/dist/node/chunks/dep-BEhTnQAI.js:65589:15)
  at node_modules/rollup/dist/es/shared/node-entry.js:19918:40
  at async PluginDriver.hookFirstAndGetPlugin (node_modules/rollup/dist/es/shared/node-entry.js:19818:28)
  at async resolveId (node_modules/rollup/dist/es/shared/node-entry.js:18509:26)
  at async ModuleLoader.resolveId (node_modules/rollup/dist/es/shared/node-entry.js:18912:15)
  at async Object.resolveId (node_modules/vite/dist/node/chunks/dep-BEhTnQAI.js:12833:10)
  at async PluginDriver.hookFirstAndGetPlugin (node_modules/rollup/dist/es/shared/node-entry.js:19818:28)
  at async resolveId (node_modules/rollup/dist/es/shared/node-entry.js:18509:26)
  at async ModuleLoader.resolveId (node_modules/rollup/dist/es/shared/node-entry.js:18912:15)
  at async node_modules/rollup/dist/es/shared/node-entry.js:19215:50 



[8:22:52 AM]  ERROR  [commonjs--resolver] No known conditions for "./routes" specifier in "vinxi" package
```

**Comment by peerreynders** [comment]
No idea what is going on there as I wasn't able to reproduce it. In an attempt to improve matters I changed some things around to upgrade to crossws 0.3.1 and SolidStart 1.0.8.

However, even if you are now able to successfully build it, the client portion will experience a  *“WebSocket connection to 'ws://localhost:3000/api/_ws/' failed: Invalid frame header”* error against the production server. It seems that, at least currently, the production server isn't as tolerant towards this style of crossws integration as the `dev` server is.

**Comment by peerreynders** [comment]
The documentation now [shows how to leverage the experimental Nitro WebSocket support](https://docs.solidjs.com/solid-start/advanced/websocket). The repo has been updated to reflect this.

This is what I get for a build now:

```shell
$ pnpm build

> solid-start-ws-demo@ build /solid-start-ws-demo
> vinxi build

vinxi v0.4.3

⚙  Building your app...
vinxi v0.4.3

⚙ Building your router ssr...

📦 Compiling ssr router...
vinxi building router ssr in http mode
vite v5.2.8 building SSR bundle for production...
✓ 23 modules transformed.
.vinxi/build/ssr/.vite/manifest.json   0.14 kB
.vinxi/build/ssr/ssr.js               18.20 kB
✓ built in 513ms
✔ build done                                                                                                                           8:07:58 p.m.
⚙ Built your router ssr successfully
vinxi v0.4.3

⚙ Building your router client...

📦 Compiling client router...
vinxi building router client in client mode
vite v5.2.8 building for production...
virtual:$vinxi/handler/client (1:115): "default" is not exported by "src/entry-client.tsx", imported by "virtual:$vinxi/handler/client".
✓ 21 modules transformed.
.vinxi/build/client/_build/server-functions-manifest.json   0.03 kB │ gzip:  0.04 kB
.vinxi/build/client/_build/.vite/manifest.json              0.17 kB │ gzip:  0.13 kB
.vinxi/build/client/_build/assets/client-xWkwqK6H.js       28.21 kB │ gzip: 11.26 kB
✓ built in 811ms
✔ build done                                                                                                                           8:08:00 p.m.
⚙ Built your router client successfully
vinxi v0.4.3

⚙ Building your router server-fns...

📦 Compiling server-fns router...
vinxi building router server-fns in http mode
vite v5.2.8 building SSR bundle for production...
✓ 19 modules transformed.
.vinxi/build/server-fns/_server/.vite/manifest.json   0.33 kB
.vinxi/build/server-fns/_server/app.mjs               4.53 kB
.vinxi/build/server-fns/_server/entry.mjs            58.76 kB
✓ built in 620ms
✔ build done                                                                                                                           8:08:01 p.m.
⚙ Built your router server-fns successfully
vinxi v0.4.3

⚙ Building your router _ws...

📦 Compiling _ws router...
vinxi building router _ws in http mode
vite v5.2.8 building SSR bundle for production...
✓ 4 modules transformed.
.vinxi/build/_ws/_ws/.vite/manifest.json  0.14 kB
.vinxi/build/_ws/_ws/_ws.js               0.69 kB
✓ built in 91ms
✔ build done                                                                                                                           8:08:02 p.m.
⚙ Built your router _ws successfully

⚙  Preparing app for node-server...
✔ Generated public .output/public                                                                                                vinxi 8:08:02 p.m.
ℹ Building Nitro Server (preset: node-server)                                                                                    vinxi 8:08:02 p.m.
✔ Nitro Server built                                                                                                             vinxi 8:08:05 p.m.
✔ You can preview this build using node .output/server/index.mjs                                                                 vinxi 8:08:05 p.m.

$ pnpm preview

> solid-start-ws-demo@ preview /solid-start-ws-demo
> node .output/server/index.mjs

Listening on http://[::]:3000
```
